apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: backend
spec:
  selector:
    app: order-ms
  ports:
    - protocol: TCP
      port: 8083 #exposed outside
      targetPort: 6123 #inside the container
  type: LoadBalancer
