apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the size of the PV as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete  # Ensures that the volume is retained after the Pod is deleted
  storageClassName: standard  # Adjust storage class according to your setup
  hostPath:
    path: /mnt/data/consul  # Local directory for storage (this works with Kind)