apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-python-wordcount
  namespace: spark-apps
spec:
  type: Python
  mode: cluster
  image: "3alaeddine/simple-spark-python:latest"  # Make sure this matches what you build and push
  imagePullPolicy: Always
  pythonVersion: "3"
  mainApplicationFile: "local:///opt/spark/work-dir/main.py"
  sparkVersion: "3.5.4"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"