apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
  namespace: db-ms
spec:
  selector:
    app: hello-python
  ports:
    - protocol: TCP
      port: 80 #exposed outside
      targetPort: 6123 #inside the container
  type: LoadBalancer
