apiVersion: v1
kind: ConfigMap
metadata:
  name: order-creator-loadtest-configmap
  namespace: backend
data:
  locustfile.py: |
    from locust import HttpUser, task, between
    
    class OrderCreatorUser(HttpUser):
        wait_time = between(1, 3)  # Wait between requests

        @task
        def create_order(self):
            self.client.post(
                "/create",
                json={"number_of_orders": 1},
                headers={"Content-Type": "application/json"}
            )