apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default
spec:
  services:
    - name: stock-service
      consumers:
        - peer: "kind"  # Replace with your secondary datacenter name

