apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mongo
spec:
  serviceName: "mongodb-headless"
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo:latest
          command:
            - mongod
            - "--replSet"
            - "rs0"
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage  # This must match the name used in the volumeMounts section
      spec:
        accessModes: [ "ReadWriteOnce" ]  # Same as in PVC definition
        resources:
          requests:
            storage: 1Gi  # Match the storage size of the PVC
        storageClassName: standard

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-0-external
  namespace: mongo
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-0
  ports:
  - port: 27017
    targetPort: 27017
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-1-external
  namespace: mongo
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-1
  ports:
  - port: 27017
    targetPort: 27017
  type: LoadBalancer