apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: mongo
spec:
  clusterIP: None  # Makes the service headless
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017