apiVersion: v1
kind: Service
metadata:
  name: premium-order-service
  namespace: backend
spec:
  selector:
    app: premium-order-ms
  ports:
    - protocol: TCP
      port: 8083 #exposed outside
      targetPort: 6124 #inside the container
  type: LoadBalancer
